{
  "2018-2019-Primeira-Liga-Mohamed Abarhoun-1989-ma MAR-Moreirense": [
    {
      "Season": "2018-2019",
      "League": "Primeira-Liga",
      "Player": "Mohamed Abarhoun",
      "BirthYear": "1989",
      "Nationality": "ma MAR",
      "Age": 29,
      "Team": "Moreirense",
      "Games": "14",
      "GamesStarts": "13",
      "Minutes": "1,171",
      "Minutes90s": "13.0",
      "Goals": "0.00",
      "Assists": "0.00",
      "npxG": "0.01",
      "xAG": "0.01",
      "PrgP": "3.62",
      "PrgCarry": "0.54",
      "PrgRec": "0.15"
    },
    {
      "Season": "2018-2019",
      "League": "Primeira-Liga",
      "Player": "Mohamed Abarhoun",
      "BirthYear": "1989",
      "Nationality": "ma MAR",
      "Age": 29,
      "Team": "Moreirense",
      "Minutes90s": "13.0",
      "Goals": "0.00",
      "Shots": "0.15",
      "ShotsOnTarget": "0.08",
      "shots_on_target_pct": "50.0",
      "shots_per90": "0.15",
      "shots_on_target_per90": "0.08",
      "goals_per_shot": "0.00",
      "goals_per_shot_on_target": "0.00",
      "npxG": "0.01",
      "npxG_per_shot": "0.05",
      "xG_net": "-0.01",
      "npxG_net": "-0.01"
    },
    {
      "Season": "2018-2019",
      "League": "Primeira-Liga",
      "Player": "Mohamed Abarhoun",
      "BirthYear": "1989",
      "Nationality": "ma MAR",
      "Age": 29,
      "Team": "Moreirense",
      "Minutes90s": "13.0",
      "Assists": "0.00",
      "TotDist": "757.3",
      "PrgDist": "347.4",
      "xAG": "0.01",
      "xA": "0.02",
      "PassesCompleted": "34.8",
      "PassesToFThird": "2.92",
      "PPA": "0.23",
      "CrsPA": "0.00",
      "PrgP": "3.62"
    },
    {
      "Season": "2018-2019",
      "League": "Primeira-Liga",
      "Player": "Mohamed Abarhoun",
      "BirthYear": "1989",
      "Nationality": "ma MAR",
      "Age": 29,
      "Team": "Moreirense",
      "Minutes90s": "13.0",
      "SCA90": "0.54",
      "GCA90": "0.00"
    },
    {
      "Season": "2018-2019",
      "League": "Primeira-Liga",
      "Player": "Mohamed Abarhoun",
      "BirthYear": "1989",
      "Nationality": "ma MAR",
      "Age": 29,
      "Team": "Moreirense",
      "Minutes90s": "13.0",
      "Tackles": "0.54",
      "TacklesW": "0.38",
      "TacklesWpct": "50.0",
      "TacklesL": "0.31",
      "TaclkesInterceptions": "1.38",
      "Clr": "4.31"
    },
    {
      "Season": "2018-2019",
      "League": "Primeira-Liga",
      "Player": "Mohamed Abarhoun",
      "BirthYear": "1989",
      "Nationality": "ma MAR",
      "Age": 29,
      "Team": "Moreirense",
      "Minutes90s": "13.0",
      "touches_def_pen_area": "5.00",
      "touches_def_3rd": "27.2",
      "touches_mid_3rd": "21.6",
      "Att3rd": "1.54",
      "Att_Pen_area": "0.54",
      "PrgCarry": "0.54",
      "CarriesFwd": "0.38",
      "CarriesIntoBox": "0.08",
      "Dispos": "0.23",
      "Recv": "29.1",
      "PrgRec": "0.15"
    },
    {
      "Season": "2018-2019",
      "League": "Primeira-Liga",
      "Player": "Mohamed Abarhoun",
      "BirthYear": "1989",
      "Nationality": "ma MAR",
      "Age": 29,
      "Team": "Moreirense",
      "Minutes90s": "13.0",
      "TacklesW": "0.38",
      "Recov": "4.69",
      "Won": "1.08",
      "Lost": "1.85",
      "Wonpct": "36.8"
    },
  ],
  "2018-2019-Primeira-Liga-Vincent Aboubakar-1992-cm CMR-Porto": [
    {
      "Season": "2018-2019",
      "League": "Primeira-Liga",
      "Player": "Vincent Aboubakar",
      "BirthYear": "1992",
      "Nationality": "cm CMR",
      "Age": 26,
      "Team": "Porto",
      "Games": "8",
      "GamesStarts": "6",
      "Minutes": "456",
      "Minutes90s": "5.1",
      "Goals": "0.78",
      "Assists": "0.20",
      "npxG": "0.80",
      "xAG": "0.10",
      "PrgP": "1.96",
      "PrgCarry": "1.18",
      "PrgRec": "6.47"
    },
    {
      "Season": "2018-2019",
      "League": "Primeira-Liga",
      "Player": "Vincent Aboubakar",
      "BirthYear": "1992",
      "Nationality": "cm CMR",
      "Age": 26,
      "Team": "Porto",
      "Minutes90s": "5.1",
      "Goals": "0.78",
      "Shots": "2.94",
      "ShotsOnTarget": "1.37",
      "shots_on_target_pct": "46.7",
      "shots_per90": "2.96",
      "shots_on_target_per90": "1.38",
      "goals_per_shot": "0.27",
      "goals_per_shot_on_target": "0.57",
      "npxG": "0.80",
      "npxG_per_shot": "0.28",
      "xG_net": "-0.02",
      "npxG_net": "-0.02"
    },
    {
      "Season": "2018-2019",
      "League": "Primeira-Liga",
      "Player": "Vincent Aboubakar",
      "BirthYear": "1992",
      "Nationality": "cm CMR",
      "Age": 26,
      "Team": "Porto",
      "Minutes90s": "5.1",
      "Assists": "0.20",
      "TotDist": "195.1",
      "PrgDist": "39.2",
      "xAG": "0.10",
      "xA": "0.06",
      "PassesCompleted": "14.7",
      "PassesToFThird": "1.18",
      "PPA": "0.59",
      "CrsPA": "0.00",
      "PrgP": "1.96"
    },
    {
      "Season": "2018-2019",
      "League": "Primeira-Liga",
      "Player": "Vincent Aboubakar",
      "BirthYear": "1992",
      "Nationality": "cm CMR",
      "Age": 26,
      "Team": "Porto",
      "Minutes90s": "5.1",
      "SCA90": "2.57",
      "GCA90": "0.39"
    },
    {
      "Season": "2018-2019",
      "League": "Primeira-Liga",
      "Player": "Vincent Aboubakar",
      "BirthYear": "1992",
      "Nationality": "cm CMR",
      "Age": 26,
      "Team": "Porto",
      "Minutes90s": "5.1",
      "Tackles": "0.59",
      "TacklesW": "0.20",
      "TacklesWpct": "",
      "TacklesL": "0.00",
      "TaclkesInterceptions": "1.18",
      "Clr": "0.98"
    },
    {
      "Season": "2018-2019",
      "League": "Primeira-Liga",
      "Player": "Vincent Aboubakar",
      "BirthYear": "1992",
      "Nationality": "cm CMR",
      "Age": 26,
      "Team": "Porto",
      "Minutes90s": "5.1",
      "touches_def_pen_area": "0.78",
      "touches_def_3rd": "2.55",
      "touches_mid_3rd": "13.9",
      "Att3rd": "18.2",
      "Att_Pen_area": "5.69",
      "PrgCarry": "1.18",
      "CarriesFwd": "0.78",
      "CarriesIntoBox": "0.98",
      "Dispos": "2.55",
      "Recv": "29.4",
      "PrgRec": "6.47"
    },
    {
      "Season": "2018-2019",
      "League": "Primeira-Liga",
      "Player": "Vincent Aboubakar",
      "BirthYear": "1992",
      "Nationality": "cm CMR",
      "Age": 26,
      "Team": "Porto",
      "Minutes90s": "5.1",
      "TacklesW": "0.20",
      "Recov": "3.53",
      "Won": "1.96",
      "Lost": "2.94",
      "Wonpct": "40.0"
    }
  ],
}

function criarNovoObjetoComArrayVazio(dados) {
  let novoObjeto = {};

  for (let chave in dados) {
    novoObjeto[chave] = [];
  }

  return novoObjeto;
}

let novoObjeto = criarNovoObjetoComArrayVazio(dados);
console.log(novoObjeto);

